### ISSUE TITLE
Docker-compose up error

### ISSUE THREAD

**Issue by akorobkin** [inveniosoftware/invenio-app-ils#1090]
Package version (if known): v1.0.0a42

## Describe the bug

When running `docker-compose -f docker-compose.full.yml up`, I get this error: 

```
  Building wheel for infinity (setup.py): started
  Building wheel for infinity (setup.py): finished with status 'done'
  Created wheel for infinity: filename=infinity-1.5-py3-none-any.whl size=3081 sha256=93adf3c03202315ef33c064945208904b5aa43dbc20e393420388c44f42c1f02
  Stored in directory: /root/.cache/pip/wheels/ed/29/a2/e785f7122ae93aef04e0616e7748ac397ec80d6ea432afbff3
Successfully built pycountry blinker ftfy click-default-group fs SQLAlchemy-Utils Flask-Login maxminddb-geolite2 python-geoip pytest-pycodestyle pytest-pydocstyle click-didyoumean SQLAlchemy-Continuum flask-limiter Flask-Mail WTForms-Alchemy future Flask-KVSession-Invenio jsmin Flask-Admin Flask-Principal node-semver pyrsistent maxminddb alembic limits speaklater infinity
Installing collected packages: six, ipython-genutils, decorator, traitlets, wcwidth, prompt-toolkit, parso, jedi, Pygments, backcall, ptyprocess, pexpect, pickleshare, IPython, click, MarkupSafe, Jinja2, itsdangerous, Werkzeug, Flask, flask-shell-ipython, blinker, invenio-base, Flask-Caching, invenio-cache, invenio-config, flask-talisman, pytz, billiard, click-didyoumean, vine, click-repl, zipp, typing-extensions, importlib-metadata, amqp, kombu, click-plugins, pytest-celery, celery, Flask-CeleryExt, uritools, limits, flask-limiter, invenio-app, msgpack, redis, invenio-celery, speaklater, babel, Flask-BabelEx, invenio-i18n, dnspython, idna, email-validator, node-semver, pynpm, pywebpack, Flask-WebpackExt, Flask-Collect, invenio-assets, Flask-Menu, Flask-Breadcrumbs, jsmin, invenio-theme, simplekv, Flask-Login, WTForms, Flask-WTF, Flask-CORS, marshmallow, webargs, invenio-rest, ua-parser, pycparser, cffi, cryptography, maxminddb, maxminddb-geolite2, Flask-KVSession-Invenio, Flask-Mail, pyjwt, Flask-Principal, passlib, Flask-Security, future, invenio-accounts, invenio-userprofiles, oauthlib, urllib3, chardet, certifi, requests, requests-oauthlib, invenio-mail, cachelib, Flask-OAuthlib, invenio-oauthclient, Flask-Admin, SQLAlchemy, Flask-SQLAlchemy, SQLAlchemy-Utils, Mako, python-editor, python-dateutil, alembic, Flask-Alembic, psycopg2-binary, SQLAlchemy-Continuum, invenio-db, invenio-admin, invenio-access, validators, infinity, intervals, WTForms-Components, WTForms-Alchemy, invenio-oauth2server, invenio-logging, pyparsing, packaging, webencodings, bleach, arrow, invenio-formatter, invenio, base32-lib, invenio-pidstore, jsonpointer, jsonpatch, jsonref, pyrsistent, attrs, jsonschema, pluggy, jsonresolver, invenio-records, invenio-indexer, invenio-jsonschemas, lxml, simplejson, dojson, invenio-oaiserver, ftfy, invenio-records-rest, click-default-group, fs, invenio-files-rest, invenio-banners, invenio-circulation, invenio-opendefinition, invenio-pages, invenio-pidrelations, python-geoip, counter-robots, invenio-queues, invenio-stats, Flask-Debugtoolbar, pycountry, sphinxcontrib-htmlhelp, snowballstemmer, sphinxcontrib-devhelp, sphinxcontrib-serializinghtml, imagesize, alabaster, sphinxcontrib-jsmath, sphinxcontrib-qthelp, docutils, sphinxcontrib-applehelp, Sphinx, lorem, mock, iniconfig, toml, py, pytest, pep517, build, check-manifest, pytest-flask, isort, pytest-isort, coverage, pytest-cov, docker-services-cli, pycodestyle, pytest-pycodestyle, pydocstyle, pytest-pydocstyle, selenium, pytest-invenio, pytest-mock, elasticsearch, elasticsearch-dsl, invenio-search, invenio-app-ils
  Running setup.py develop for invenio-app-ils
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
flask 1.1.4 requires click<8.0,>=5.1, but you'll have click 8.0.0 which is incompatible.
flask 1.1.4 requires itsdangerous<2.0,>=0.24, but you'll have itsdangerous 2.0.1 which is incompatible.
celery 5.0.5 requires click<8.0,>=7.0, but you'll have click 8.0.0 which is incompatible.
docker-services-cli 0.3.0 requires click<8.0,>=7.0, but you'll have click 8.0.0 which is incompatible.
Successfully installed Flask-1.1.4 Flask-Admin-1.5.8 Flask-Alembic-2.0.1 Flask-BabelEx-0.9.4 Flask-Breadcrumbs-0.5.1 Flask-CORS-3.0.10 Flask-Caching-1.10.1 Flask-CeleryExt-0.3.4 Flask-Collect-1.2.2 Flask-Debugtoolbar-0.11.0 Flask-KVSession-Invenio-0.6.3 Flask-Login-0.4.1 Flask-Mail-0.9.1 Flask-Menu-0.7.2 Flask-OAuthlib-0.9.6 Flask-Principal-0.4.0 Flask-SQLAlchemy-2.4.4 Flask-Security-3.0.0 Flask-WTF-0.14.3 Flask-WebpackExt-1.0.2 IPython-7.16.1 Jinja2-2.11.3 Mako-1.1.4 MarkupSafe-1.1.1 Pygments-2.9.0 SQLAlchemy-1.3.24 SQLAlchemy-Continuum-1.3.11 SQLAlchemy-Utils-0.35.0 Sphinx-4.0.1 WTForms-2.3.3 WTForms-Alchemy-0.17.0 WTForms-Components-0.10.5 Werkzeug-1.0.1 alabaster-0.7.12 alembic-1.6.2 amqp-5.0.6 arrow-1.1.0 attrs-21.2.0 babel-2.9.1 backcall-0.2.0 base32-lib-1.0.2 billiard-3.6.4.0 bleach-3.3.0 blinker-1.4 build-0.3.1.post1 cachelib-0.1.1 celery-5.0.5 certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 check-manifest-0.46 click-8.0.0 click-default-group-1.2.2 click-didyoumean-0.0.3 click-plugins-1.1.1 click-repl-0.1.6 counter-robots-2018.6 coverage-5.5 cryptography-3.4.7 decorator-5.0.9 dnspython-2.1.0 docker-services-cli-0.3.0 docutils-0.17.1 dojson-1.4.0 elasticsearch-7.12.1 elasticsearch-dsl-7.3.0 email-validator-1.1.2 flask-limiter-1.1.0 flask-shell-ipython-0.4.1 flask-talisman-0.5.0 fs-0.5.4 ftfy-6.0.1 future-0.18.2 idna-2.10 imagesize-1.2.0 importlib-metadata-4.0.1 infinity-1.5 iniconfig-1.1.1 intervals-0.9.1 invenio-3.4.1 invenio-access-1.4.2 invenio-accounts-1.4.4 invenio-admin-1.3.0 invenio-app-1.3.1 invenio-app-ils invenio-assets-1.2.6 invenio-banners-1.0.0a1 invenio-base-1.2.4 invenio-cache-1.1.0 invenio-celery-1.2.2 invenio-circulation-1.0.0a31 invenio-config-1.0.3 invenio-db-1.0.9 invenio-files-rest-1.2.0 invenio-formatter-1.1.0 invenio-i18n-1.3.0 invenio-indexer-1.2.1 invenio-jsonschemas-1.1.2 invenio-logging-1.3.0 invenio-mail-1.0.2 invenio-oaiserver-1.2.0 invenio-oauth2server-1.3.2 invenio-oauthclient-1.4.4 invenio-opendefinition-1.0.0a9 invenio-pages-1.0.0a5 invenio-pidrelations-1.0.0a7 invenio-pidstore-1.2.2 invenio-queues-1.0.0a3 invenio-records-1.4.0 invenio-records-rest-1.8.0 invenio-rest-1.2.3 invenio-search-1.3.1 invenio-stats-1.0.0a18 invenio-theme-1.3.8 invenio-userprofiles-1.2.2 ipython-genutils-0.2.0 isort-5.8.0 itsdangerous-2.0.1 jedi-0.18.0 jsmin-2.2.2 jsonpatch-1.32 jsonpointer-2.1 jsonref-0.2 jsonresolver-0.3.1 jsonschema-3.2.0 kombu-5.0.2 limits-1.5.1 lorem-0.1.1 lxml-4.6.3 marshmallow-3.12.1 maxminddb-2.0.3 maxminddb-geolite2-2018.703 mock-4.0.3 msgpack-1.0.2 node-semver-0.1.1 oauthlib-2.1.0 packaging-20.9 parso-0.8.2 passlib-1.7.4 pep517-0.10.0 pexpect-4.8.0 pickleshare-0.7.5 pluggy-0.13.1 prompt-toolkit-3.0.18 psycopg2-binary-2.8.6 ptyprocess-0.7.0 py-1.10.0 pycodestyle-2.7.0 pycountry-20.7.3 pycparser-2.20 pydocstyle-6.1.1 pyjwt-2.1.0 pynpm-0.1.2 pyparsing-2.4.7 pyrsistent-0.17.3 pytest-6.2.4 pytest-celery-0.0.0 pytest-cov-2.12.0 pytest-flask-1.2.0 pytest-invenio-1.4.2 pytest-isort-2.0.0 pytest-mock-3.6.1 pytest-pycodestyle-2.2.0 pytest-pydocstyle-2.2.0 python-dateutil-2.8.1 python-editor-1.0.4 python-geoip-1.2 pytz-2021.1 pywebpack-1.2.0 redis-3.5.3 requests-2.25.1 requests-oauthlib-1.1.0 selenium-3.141.0 simplejson-3.17.2 simplekv-0.14.1 six-1.16.0 snowballstemmer-2.1.0 speaklater-1.3 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4 toml-0.10.2 traitlets-4.3.3 typing-extensions-3.10.0.0 ua-parser-0.10.0 uritools-3.0.2 urllib3-1.26.4 validators-0.18.2 vine-5.0.0 wcwidth-0.2.5 webargs-5.5.3 webencodings-0.5.1 zipp-3.4.1
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 8.0.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('click<8.0,>=5.1'), {'Flask'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ils", line 33, in <module>
    sys.exit(load_entry_point('invenio-app-ils', 'console_scripts', 'ils')())
  File "/usr/local/bin/ils", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 166, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/invenio_app/__init__.py", line 172, in <module>
    from .ext import InvenioApp
  File "/usr/local/lib/python3.6/site-packages/invenio_app/ext.py", line 15, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 8.0.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('click<8.0,>=5.1'), {'Flask'})

```

## Steps to Reproduce
1.
```
git clone https://github.com/inveniosoftware/invenio-app-ils invenioils
cd invenioils
docker-compose -f docker-compose.full.yml up
```
2. See error

## Additional context

I simply tried to run preview on my Debian 10 buster freshly-installed Linux OS.

**Comment by nethricia** [comment]
i have this problem too

seems like it was the click version dependency problem that installed when the setup is running, the error said we need click <8.0.0 for flask etc.

**Comment by tflhyl** [comment]
same issue, any workaround?
