### ISSUE TITLE
Installation/setup issue

### ISSUE THREAD

**Issue by tkfischer** [inveniosoftware/invenio-app-ils#1131]
Package: Latest version

When I run the scripts/setup, I am getting this error

ils roles create admin...
Role "admin" created successfully.
ils roles create librarian...
Role "librarian" created successfully.
ils users create patron1@test.ch -a --password=123456...
Traceback (most recent call last):
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/bin/ils", line 33, in <module>
    sys.exit(load_entry_point('invenio-app-ils', 'console_scripts', 'ils')())
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 829, in call
    return self.main(*args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/tkfischer/iis/invenio/invenio-app-ils/invenio_app_ils/cli.py", line 1895, in setup
    run_command("users create patron1@test.ch -a --password=123456")
  File "/Users/tkfischer/iis/invenio/invenio-app-ils/invenio_app_ils/cli.py", line 1873, in run_command
    res = runner.invoke(cli, command, catch_exceptions=catch_exceptions)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/flask/testing.py", line 283, in invoke
    return super(FlaskCliRunner, self).invoke(cli, args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/testing.py", line 329, in invoke
    cli.main(args=args or (), prog_name=prog_name, **extra)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/invenio_accounts/cli.py", line 30, in wrapper
    fn(*args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/invenio_accounts/cli.py", line 55, in users_create
    form = ConfirmRegisterForm(MultiDict(kwargs), csrf_enabled=False)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/flask_security/forms.py", line 94, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/flask_wtf/form.py", line 73, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/flask_wtf/csrf.py", line 148, in generate_csrf_token
    secret_key=self.meta.csrf_secret, token_key=self.meta.csrf_field_name
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/flask_wtf/csrf.py", line 52, in generate_csrf
    if field_name not in session:
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/werkzeug/local.py", line 379, in <lambda>
    __contains__ = lambda x, i: i in x._get_current_object()
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/tkfischer/iis/invenio/virtualenvs/current/lib/python3.7/site-packages/flask/globals.py", line 38, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.

--

I am on MacbookPro/Intel with BigSur and Python3.7. I followed the instructions and the bootstrap seemed to run ok.
Can you please look into it. Thanks.

**Comment by kpsherva** [comment]
Hello @tkfischer! thank you for your interest in ILS and thank you for reporting the issue.
We will check on our side what might be causing the problem and we will let you know once we have more information.
