### ISSUE TITLE
More problems running the Docker preview

### ISSUE THREAD

**Issue by thoni56** [inveniosoftware/invenio-app-ils#1177]
Package version (if known): v1.0.0rc1 - https://github.com/inveniosoftware/invenio-app-ils/commit/95feace0e3718cf4bf0c4230fd0d57d9079dbdd0
## Describe the bug
- docker container (backend) hangs in a loop with an error in SQL
- there is no `./scripts/setup` to fill demo data

## Steps to Reproduce
1. Update Python version in `docker/backend/Dockerfile` to 3.7 as per #1176 
1. Follow instructions on `https://invenioils.docs.cern.ch/preview/`
2. See `invenio-app-ils-backend-1` repeatedly fail with a traceback (provided below)
3. After `docker exec -it ...` trying to run `./script/setup` but there is no such script.

## Expected behavior
Getting a demo/preview instance started.

## Additional context

Traceback:
```
invenio-app-ils-backend-1   | [pid: 11|app: 0|req: 2881/2952] 172.20.0.10 () {40 vars in 433 bytes} [Sat D
ec 17 14:18:31 2022] HEAD /ping => generated 0 bytes in 11 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 sw
itches on core 0)
invenio-app-ils-db-1        | 2022-12-17 14:18:33.279 UTC [75] ERROR:  relation "pages_page" does not exis
t at character 347
invenio-app-ils-db-1        | 2022-12-17 14:18:33.279 UTC [75] STATEMENT:  SELECT pages_page.created AS pa
ges_page_created, pages_page.updated AS pages_page_updated, pages_page.id AS pages_page_id, pages_page.url
 AS pages_page_url, pages_page.title AS pages_page_title, pages_page.content AS pages_page_content, pages_
page.description AS pages_page_description, pages_page.template_name AS pages_page_template_name
invenio-app-ils-backend-1   | [2022-12-17 14:18:33,279] WARNING in views: Pages were not loaded.
invenio-app-ils-db-1        |   FROM pages_page
invenio-app-ils-backend-1   | Traceback (most recent call last):
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", l
ine 1277, in _execute_context
invenio-app-ils-backend-1   |     cursor, statement, parameters, context
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py"
, line 608, in do_execute
invenio-app-ils-backend-1   |     cursor.execute(statement, parameters)
invenio-app-ils-backend-1   | psycopg2.errors.UndefinedTable: relation "pages_page" does not exist
invenio-app-ils-backend-1   | LINE 2: FROM pages_page
invenio-app-ils-backend-1   |              ^
invenio-app-ils-backend-1   |
invenio-app-ils-backend-1   |
invenio-app-ils-backend-1   | The above exception was the direct cause of the following exception:
invenio-app-ils-backend-1   |
invenio-app-ils-backend-1   | Traceback (most recent call last):
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2091, in
__call__
invenio-app-ils-backend-1   |     return self.wsgi_app(environ, start_response)
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/werkzeug/middleware/dispatche
r.py", line 78, in __call__
invenio-app-ils-backend-1   |     return app(environ, start_response)
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2076, in
wsgi_app
invenio-app-ils-backend-1   |     response = self.handle_exception(e)
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in
wsgi_app
invenio-app-ils-backend-1   |     response = self.full_dispatch_request()
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1511, in
full_dispatch_request
invenio-app-ils-backend-1   |     self.try_trigger_before_first_request_functions()
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1563, in
try_trigger_before_first_request_functions
invenio-app-ils-backend-1   |     self.ensure_sync(func)()
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/invenio_pages/views.py", line
 49, in preload_pages
invenio-app-ils-backend-1   |     _add_url_rule([page.url for page in Page.query.all()])
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", lin
e 3373, in all
invenio-app-ils-backend-1   |     return list(self)
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", lin
e 3535, in __iter__
invenio-app-ils-backend-1   |     return self._execute_and_instances(context)
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", lin
e 3560, in _execute_and_instances
invenio-app-ils-backend-1   |     result = conn.execute(querycontext.statement, self._params)
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", l
ine 1011, in execute
invenio-app-ils-backend-1   |     return meth(self, multiparams, params)
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py",
line 298, in _execute_on_connection
invenio-app-ils-backend-1   |     return connection._execute_clauseelement(self, multiparams, params)
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", l
ine 1130, in _execute_clauseelement
invenio-app-ils-backend-1   |     distilled_params,
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", l
ine 1317, in _execute_context
invenio-app-ils-backend-1   |     e, statement, parameters, cursor, context
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", l
ine 1511, in _handle_dbapi_exception
invenio-app-ils-backend-1   |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", l
ine 182, in raise_
invenio-app-ils-backend-1   |     raise exception
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", l
ine 1277, in _execute_context
invenio-app-ils-backend-1   |     cursor, statement, parameters, context
invenio-app-ils-backend-1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py"
, line 608, in do_execute
invenio-app-ils-backend-1   |     cursor.execute(statement, parameters)
invenio-app-ils-backend-1   | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "
pages_page" does not exist
invenio-app-ils-frontend-1  | 2022/12/17 14:18:33 [error] 29#29: *5905 upstream prematurely closed connect
ion while reading response header from upstream, client: 172.20.0.10, server: _, request: "HEAD /ping HTTP
/1.1", upstream: "uwsgi://172.20.0.8:5000", host: "localhost"
invenio-app-ils-backend-1   | LINE 2: FROM pages_page
invenio-app-ils-frontend-1  | 172.20.0.10 - - [17/Dec/2022:14:18:33 +0000] "HEAD /ping HTTP/1.1" 502 0 "-"
 "-" "-"
invenio-app-ils-backend-1   |              ^
invenio-app-ils-backend-1   |
invenio-app-ils-backend-1   | [SQL: SELECT pages_page.created AS pages_page_created, pages_page.updated AS
 pages_page_updated, pages_page.id AS pages_page_id, pages_page.url AS pages_page_url, pages_page.title AS
 pages_page_title, pages_page.content AS pages_page_content, pages_page.description AS pages_page_descript
ion, pages_page.template_name AS pages_page_template_name
invenio-app-ils-backend-1   | FROM pages_page]
invenio-app-ils-backend-1   | (Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by thehale** [comment]
> there is no ./scripts/setup to fill demo data

This is still true. There are scripts called `bootstrap` and `build_assets` but attempting to run them after SSH-ing into the container fails due to permission errors:

<details>

```
$ docker exec -it invenio-app-ils_backend_1 /bin/bash
invenio@e0b489b1df26:/opt/invenio_app_ils/src$ ./scripts/build_assets 
/usr/local/lib/python3.6/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py:15: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  import cryptography
/usr/local/lib/python3.6/site-packages/flask_caching/__init__.py:241: DeprecationWarning: Using the initialization functions in flask_caching.backend is deprecated.  Use the a full path to backend classes directly.
  category=DeprecationWarning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'from', 'dump_to': 'from'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/invenio_rest/ext.py:30: FutureWarning: CSRF validation will be enabled by default in the version 1.3.x
  self.init_app(app)

/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/clsregistry.py:129: SAWarning: This declarative base already contains a class with the same class name and module name as sqlalchemy_continuum.model_builder.RecordMetadataVersion, and will be replaced in the string-lookup table.
  % (item.__module__, item.__name__)

/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/clsregistry.py:129: SAWarning: This declarative base already contains a class with the same class name and module name as sqlalchemy_continuum.model_builder.PageVersion, and will be replaced in the string-lookup table.
  % (item.__module__, item.__name__)

/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/clsregistry.py:129: SAWarning: This declarative base already contains a class with the same class name and module name as sqlalchemy_continuum.model_builder.PageListVersion, and will be replaced in the string-lookup table.
  % (item.__module__, item.__name__)

/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/properties.py:249: SAWarning: On mapper mapped class RecordMetadataVersion->records_metadata_version, primary key column 'records_metadata_version.transaction_id' is being combined with distinct primary key column 'records_metadata_version.transaction_id' in attribute 'transaction_id'. Use explicit properties to give each column its own mapped attribute name.
  % (self.parent, self.columns[1], self.columns[0], self.key)

/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/properties.py:249: SAWarning: On mapper mapped class PageVersion->pages_page_version, primary key column 'pages_page_version.transaction_id' is being combined with distinct primary key column 'pages_page_version.transaction_id' in attribute 'transaction_id'. Use explicit properties to give each column its own mapped attribute name.
  % (self.parent, self.columns[1], self.columns[0], self.key)

/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/properties.py:249: SAWarning: On mapper mapped class PageListVersion->pages_pagelist_version, primary key column 'pages_pagelist_version.transaction_id' is being combined with distinct primary key column 'pages_pagelist_version.transaction_id' in attribute 'transaction_id'. Use explicit properties to give each column its own mapped attribute name.
  % (self.parent, self.columns[1], self.columns[0], self.key)

/usr/local/lib/python3.6/site-packages/flask_caching/__init__.py:241: DeprecationWarning: Using the initialization functions in flask_caching.backend is deprecated.  Use the a full path to backend classes directly.
  category=DeprecationWarning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:184: RemovedInMarshmallow4Warning: The 'missing' argument to fields is deprecated. Use 'load_default' instead.
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'partNumber', 'location': 'query'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'Content-Length', 'location': 'headers'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'Content-Type', 'location': 'headers'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'Content-MD5', 'location': 'headers'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': '_chunkNumber', 'location': 'form'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': '_currentChunkSize', 'location': 'form'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'file', 'location': 'files'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': '_totalSize', 'location': 'form'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'location': 'query'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'location': 'query', 'load_from': 'versionId'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'location': 'query', 'load_from': 'uploadId'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'locations': ('query', 'json')}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'locations': ('query', 'json'), 'load_from': 'partSize'}
  RemovedInMarshmallow4Warning,

Collect static from blueprints.
/usr/local/lib/python3.6/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py:15: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  import cryptography
/usr/local/lib/python3.6/site-packages/kombu/utils/compat.py:93: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for ep in importlib_metadata.entry_points().get(namespace, [])

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'from', 'dump_to': 'from'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/flask_caching/__init__.py:241: DeprecationWarning: Using the initialization functions in flask_caching.backend is deprecated.  Use the a full path to backend classes directly.
  category=DeprecationWarning,

/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/clsregistry.py:129: SAWarning: This declarative base already contains a class with the same class name and module name as sqlalchemy_continuum.model_builder.RecordMetadataVersion, and will be replaced in the string-lookup table.
  % (item.__module__, item.__name__)

/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/clsregistry.py:129: SAWarning: This declarative base already contains a class with the same class name and module name as sqlalchemy_continuum.model_builder.PageVersion, and will be replaced in the string-lookup table.
  % (item.__module__, item.__name__)

/usr/local/lib/python3.6/site-packages/sqlalchemy/ext/declarative/clsregistry.py:129: SAWarning: This declarative base already contains a class with the same class name and module name as sqlalchemy_continuum.model_builder.PageListVersion, and will be replaced in the string-lookup table.
  % (item.__module__, item.__name__)

/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/properties.py:249: SAWarning: On mapper mapped class RecordMetadataVersion->records_metadata_version, primary key column 'records_metadata_version.transaction_id' is being combined with distinct primary key column 'records_metadata_version.transaction_id' in attribute 'transaction_id'. Use explicit properties to give each column its own mapped attribute name.
  % (self.parent, self.columns[1], self.columns[0], self.key)

/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/properties.py:249: SAWarning: On mapper mapped class PageVersion->pages_page_version, primary key column 'pages_page_version.transaction_id' is being combined with distinct primary key column 'pages_page_version.transaction_id' in attribute 'transaction_id'. Use explicit properties to give each column its own mapped attribute name.
  % (self.parent, self.columns[1], self.columns[0], self.key)

/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/properties.py:249: SAWarning: On mapper mapped class PageListVersion->pages_pagelist_version, primary key column 'pages_pagelist_version.transaction_id' is being combined with distinct primary key column 'pages_pagelist_version.transaction_id' in attribute 'transaction_id'. Use explicit properties to give each column its own mapped attribute name.
  % (self.parent, self.columns[1], self.columns[0], self.key)

/usr/local/lib/python3.6/site-packages/invenio_rest/ext.py:30: FutureWarning: CSRF validation will be enabled by default in the version 1.3.x
  self.init_app(app)

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:184: RemovedInMarshmallow4Warning: The 'missing' argument to fields is deprecated. Use 'load_default' instead.
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'partNumber', 'location': 'query'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'Content-Length', 'location': 'headers'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'Content-Type', 'location': 'headers'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'Content-MD5', 'location': 'headers'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': '_chunkNumber', 'location': 'form'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': '_currentChunkSize', 'location': 'form'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': 'file', 'location': 'files'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'load_from': '_totalSize', 'location': 'form'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'location': 'query'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'location': 'query', 'load_from': 'versionId'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'location': 'query', 'load_from': 'uploadId'}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'locations': ('query', 'json')}
  RemovedInMarshmallow4Warning,

/usr/local/lib/python3.6/site-packages/marshmallow/fields.py:222: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'locations': ('query', 'json'), 'load_from': 'partSize'}
  RemovedInMarshmallow4Warning,

npm ERR! correctMkdir failed to make directory /home/invenio/.npm/_locks
npm WARN eslint-config-react-app@5.2.1 requires a peer of @typescript-eslint/eslint-plugin@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of @typescript-eslint/parser@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of eslint@6.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of eslint-plugin-flowtype@3.x || 4.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.2.1 requires a peer of eslint-plugin-react-hooks@1.x || 2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@14.1.1 requires a peer of eslint-plugin-node@>=9.1.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/invenio
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/home/invenio'
npm ERR!  [Error: EACCES: permission denied, mkdir '/home/invenio'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/invenio'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
Traceback (most recent call last):
  File "/usr/local/bin/ils", line 33, in <module>
    sys.exit(load_entry_point('invenio-app-ils', 'console_scripts', 'ils')())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 601, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 445, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_webpackext/cli.py", line 72, in buildall
    current_webpack.project.buildall()
  File "/usr/local/lib/python3.6/site-packages/pywebpack/project.py", line 141, in buildall
    super(WebpackTemplateProject, self).buildall()
  File "/usr/local/lib/python3.6/site-packages/pywebpack/project.py", line 69, in buildall
    self.install()
  File "/usr/local/lib/python3.6/site-packages/pywebpack/helpers.py", line 48, in inner
    raise RuntimeError("Process exited with code {}".format(exit_code))
RuntimeError: Process exited with code 243
```

</details>
